"""Add color_hex to categoria_dieta

Revision ID: 001_add_color_hex
Revises: 
Create Date: 2026-05-16 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001_add_color_hex'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categoria_dieta', sa.Column('color_hex', sa.String(length=7), nullable=False, server_default='#FF6B6B'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categoria_dieta', 'color_hex')
    # ### end Alembic commands ###
