"""Add propietario_id to establecimiento

Revision ID: 002_add_propietario_id
Revises: 001_add_color_hex
Create Date: 2026-05-16 12:05:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002_add_propietario_id'
down_revision = '001_add_color_hex'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('establecimiento', sa.Column('propietario_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_establecimiento_propietario_id', 'establecimiento', 'usuarios', ['propietario_id'], ['id_usuario'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_establecimiento_propietario_id', 'establecimiento', type_='foreignkey')
    op.drop_column('establecimiento', 'propietario_id')
    # ### end Alembic commands ###
