"""Make id_tipo_item_menu nullable in item_menu

Revision ID: 003_nullable_tipo_item
Revises: 002_add_propietario_id_to_establecimiento
Create Date: 2026-05-16 14:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003_nullable_tipo_item'
down_revision = '002_add_propietario_id'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Hacer que id_tipo_item_menu sea nullable
    op.alter_column('item_menu', 'id_tipo_item_menu',
               existing_type=sa.Integer(),
               nullable=True,
               existing_server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revertir a no-nullable
    op.alter_column('item_menu', 'id_tipo_item_menu',
               existing_type=sa.Integer(),
               nullable=False,
               existing_server_default=None)
    # ### end Alembic commands ###
